# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: Skilli  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'          <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wakanda: Masajja Story</title>
    <style>
        /* General reset and body styles */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f7f7f7;
            color: #333;
            line-height: 1.6;
            padding: 0;
            overflow-x: hidden;
        }
        a {
            text-decoration: none;
            color: inherit;
        }

        /* Header */
        header {
            background: linear-gradient(135deg, #2980b9, #2c3e50);
            color: #fff;
            padding: 60px 20px;
            text-align: center;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
        }
        header h1 {
            font-size: 3rem;
            margin-bottom: 10px;
        }
        header p {
            font-size: 1.2rem;
            font-weight: 400;
        }

        /* Story Section */
        .story {
            padding: 50px 20px;
            background-color: #fff;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.05);
            margin: 20px;
            border-radius: 10px;
            max-width: 1200px;
            margin-left: auto;
            margin-right: auto;
        }
        .story h2 {
            font-size: 2.5rem;
            color: #2980b9;
            margin-bottom: 20px;
        }
        .story p {
            font-size: 1.1rem;
            color: #555;
            line-height: 1.8;
        }

        /* Image Section */
        .images {
            display: flex;
            justify-content: center;
            gap: 20px;
            margin-top: 30px;
            flex-wrap: wrap;
        }
        .images img {
            width: 100%;
            max-width: 500px;
            border-radius: 15px;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s ease;
        }
        .images img:hover {
            transform: scale(1.05);
        }

        /* Contact Section */
        .contact {
            text-align: center;
            background: #2c3e50;
            color: white;
            padding: 40px;
            margin-top: 30px;
            border-radius: 10px;
        }
        .contact h2 {
            font-size: 2.5rem;
            margin-bottom: 15px;
        }
        .contact p {
            font-size: 1.1rem;
            margin: 10px 0;
        }
        .contact a {
            color: #ecf0f1;
            font-weight: bold;
            transition: color 0.3s ease;
        }
        .contact a:hover {
            color: #1abc9c;
        }

        /* Footer */
        footer {
            text-align: center;
            padding: 20px;
            background-color: #1f2a44;
            color: white;
            font-size: 1rem;
            position: fixed;
            width: 100%;
            bottom: 0;
        }
    </style>
</head>
<body>

    <!-- Header -->
    <header>
        <h1>Wakanda: Masajja</h1>
        <p>Near Pentagon Stage</p>
    </header>

    <!-- Story Section -->
    <section class="story">
        <h2>The Struggles of Ghetto People</h2>
        <p>In the heart of Masajja, near the Pentagon stage, the community faces immense challenges. Despite the odds, these brave souls strive to make a living and chase their dreams. The streets are filled with the hustle of street vendors, hopeful artists, and families that refuse to give up. Though the struggles are real, there is an undeniable strength in the spirit of these people. They rise above the adversity with resilience and courage. This is their story.</p>
    </section>

    <!-- Image Section -->
    <section class="images">
        <h2>Real Moments: The Heart of the Ghetto</h2>
        <div>
            <img src="https://example.com/path-to-your-image.jpg" alt="Ghetto Life" />
            <p>These images reflect the raw emotions and moments of the people who continue to fight for a better life, one step at a time.</p>
        </div>
        <div>
            <img src="https://example.com/second-image.jpg" alt="Struggling for a Living" />
        </div>
    </section>

    <!-- Contact Section -->
    <section class="contact">
        <h2>Get in Touch</h2>
        <p>Email: <a href="mailto:kingbullet588@gmail.com">kingbullet588@gmail.com</a></p>
        <p>Contact: <a href="tel:+256762438887">+256 762 438 887</a></p>
    </section>

    <!-- Footer -->
    <footer>
        <p>© 2025 Wakanda - Masajja Community</p>
    </footer>

</body>
</html>      # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
